const LOADED_FILMS_SUCCESS = 'LOADED_FILMS_SUCCESS';
const LOADED_FILMS_FAILURE = 'LOADED_FILMS_FAILURE';

const SET_USER_LOGIN = 'SET_USER_LOGIN';
const CLEAR_USER = 'CLEAR_USER';
const SET_USER = 'SET_USER';

const SET_FILTER = 'SET_FILTER';

export {
    LOADED_FILMS_SUCCESS,
    LOADED_FILMS_FAILURE,
    SET_USER_LOGIN,
    CLEAR_USER,
    SET_USER,
    SET_FILTER
};
