export const LOADED_FILMS_SUCCESS = 'LOADED_FILMS_SUCCESS';
export const LOADED_FILMS_FAILURE = 'LOADED_FILMS_FAILURE';

export const LOADED_GENRES_SUCCESS = 'LOADED_GENRES_SUCCESS';
export const LOADED_GENRES_FAILURE = 'LOADED_GENRES_FAILURE';

export const LOADED_CHANNELS_SUCCESS = 'LOADED_CHANNELS_SUCCESS';
export const LOADED_CHANNELS_FAILURE = 'LOADED_CHANNELS_FAILURE';

export const LOADED_COMMENTS_SUCCESS = 'LOADED_COMMENTS_SUCCESS';
export const LOADED_COMMENTS_FAILURE = 'LOADED_COMMENTS_FAILURE';

export const ADD_COMMENT = 'ADD_COMMENT';
export const REMOVE_COMMENT = 'REMOVE_COMMENT';

export const SET_USER_LOGIN = 'SET_USER_LOGIN';
export const CLEAR_USER = 'CLEAR_USER';
export const SET_USER = 'SET_USER';

export const SET_FILTER = 'SET_FILTER';

