const LOADED_FILMS_SUCCESS = 'LOADED_FILMS_SUCCESS';
const LOADED_FILMS_FAILURE = 'LOADED_FILMS_FAILURE';

const LOADED_GENRES_SUCCESS = 'LOADED_GENRES_SUCCESS';
const LOADED_GENRES_FAILURE = 'LOADED_GENRES_FAILURE';

const LOADED_CHANNELS_SUCCESS = 'LOADED_CHANNELS_SUCCESS';
const LOADED_CHANNELS_FAILURE = 'LOADED_CHANNELS_FAILURE';

const SET_USER_LOGIN = 'SET_USER_LOGIN';
const CLEAR_USER = 'CLEAR_USER';
const SET_USER = 'SET_USER';

const SET_FILTER = 'SET_FILTER';

export {
    LOADED_CHANNELS_SUCCESS,
    LOADED_CHANNELS_FAILURE,
    LOADED_FILMS_SUCCESS,
    LOADED_FILMS_FAILURE,
    LOADED_GENRES_SUCCESS,
    LOADED_GENRES_FAILURE,
    SET_USER_LOGIN,
    CLEAR_USER,
    SET_USER,
    SET_FILTER
};
